'use client';

import React from 'react';
import { ArrowLeft, AlertTriangle } from 'lucide-react';

interface TermsOfServiceProps {
  onNavigate: (page: string) => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onNavigate }) => {
  return (
    <div className="min-h-screen bg-[#EAE9E5] font-serif text-gray-900 relative">
      <div className="sticky top-0 z-20 bg-[#EAE9E5]/90 backdrop-blur-md border-b border-gray-200/50">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={() => onNavigate('home')} className="group flex items-center text-sm font-bold text-gray-500 hover:text-[#FF5A36] transition-colors font-sans">
            <ArrowLeft size={18} className="mr-2 group-hover:-translate-x-1 transition-transform" />
            Back to Home
          </button>
          <span className="text-sm font-bold text-gray-400 font-sans">Terms of Service</span>
        </div>
      </div>

      <main className="max-w-3xl mx-auto px-6 py-12 md:py-20">
        <div className="mb-12">
          <h1 className="text-4xl md:text-5xl font-serif font-medium text-gray-900 mb-6 tracking-tight">Terms of Service</h1>
          <p className="text-gray-500 text-sm font-medium font-sans">Last updated: Dec 25, 2025</p>
        </div>

        <div className="prose prose-lg max-w-none text-gray-700 leading-relaxed space-y-12 font-serif">
          <section>
            <p className="text-lg text-gray-800 font-medium">
              Welcome to Mini Doc. By using our website and services, you agree to these Terms of Service. Please read them carefully.
            </p>
          </section>

          <section className="bg-amber-50 p-8 rounded-2xl border border-amber-100 relative overflow-hidden">
            <div className="absolute top-0 left-0 w-1 h-full bg-amber-400"></div>
            <div className="flex items-start gap-4">
              <div className="mt-1 p-2 bg-amber-100 text-amber-700 rounded-lg shrink-0">
                <AlertTriangle size={24} />
              </div>
              <div>
                <h3 className="text-xl font-bold text-amber-900 mb-2 font-serif">Important Disclaimer: Not Legal Advice</h3>
                <p className="text-amber-900/80 text-base leading-relaxed">
                  <strong>Mini Doc is an Artificial Intelligence tool, not a law firm, immigration consultancy, or government agency.</strong>
                </p>
                <p className="text-amber-900/80 text-base leading-relaxed mt-4">
                  The documents, summaries, and suggestions generated by Mini Doc are for informational and organizational purposes only. They do not constitute legal advice.
                </p>
              </div>
            </div>
          </section>

          <section>
            <h3 className="text-2xl font-serif font-medium text-gray-900 mb-4">1. Services Provided</h3>
            <p>
              Mini Doc provides an AI-powered platform to assist users in organizing files, drafting letters, and managing schedules. We grant you a limited, non-exclusive, non-transferable license to use our Services.
            </p>
          </section>

          <section>
            <h3 className="text-2xl font-serif font-medium text-gray-900 mb-4">2. User Responsibilities</h3>
            <p>You agree to use Mini Doc responsibly. You must not:</p>
            <ul className="list-disc pl-5 space-y-2 mt-4 marker:text-[#FF5A36]">
              <li>Upload content that is illegal, harmful, or violates the rights of others.</li>
              <li>Use the platform to generate fraudulent documents or mislead others.</li>
              <li>Attempt to reverse engineer or harm the infrastructure of our Services.</li>
              <li>Share your account credentials with others.</li>
            </ul>
          </section>

          <section>
            <h3 className="text-2xl font-serif font-medium text-gray-900 mb-4">3. Subscriptions & Billing</h3>
            <p>Some features of Mini Doc require a paid subscription.</p>
            <ul className="list-disc pl-5 space-y-2 mt-4 marker:text-[#FF5A36]">
              <li><strong>Billing Cycle:</strong> Subscriptions are billed in advance on a recurring basis.</li>
              <li><strong>Cancellation:</strong> You may cancel your subscription at any time.</li>
              <li><strong>Refunds:</strong> Refunds are handled on a case-by-case basis.</li>
            </ul>
          </section>

          <section>
            <h3 className="text-2xl font-serif font-medium text-gray-900 mb-4">4. Contact Information</h3>
            <p>For legal inquiries, please contact us at:</p>
            <p className="mt-2 font-bold text-[#FF5A36] font-sans">legal@minidoc.app</p>
          </section>
        </div>
      </main>

      <footer className="py-12 border-t border-gray-200/50 mt-12 text-center">
        <p className="text-sm text-gray-400 font-sans">© 2026 Mini Doc. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default TermsOfService;
